spring.application.name=dispatch-queue-service
server.port=8082
# Conexión al contenedor Docker de SQL Server
# Cambia esto: jdbc:sqlserver://localhost:1433;...
# Por esto:
spring.datasource.url=jdbc:sqlserver://dispatch-db:1433;databaseName=dispatch_db;encrypt=true;trustServerCertificate=true;authenticationMethod=SqlPassword;
spring.datasource.username=sa
spring.datasource.password=SistemasUtp2026Sistemas
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Forzar dialecto base para compatibilidad con contenedores
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Inicialización segura post-creación de tablas

app.services.audit.url=http://audit-history-service:8083/api/v1/audit/logs
